OAI-64: Make sure dataframe prediction size is valid
openimis/openimis-be-claim_ai_py pull request #25
Opened 2022-03-02 17:48 UTC by dborowiecki

2022-03-04 12:15 UTC, dragos-dobre requested changes

2022-03-04 12:15 UTC, dragos-dobre commented on claim_ai/evaluation/stored_resource_evaluation.py
> +    # @classmethod
Is this commented code still needed?

2022-03-04 15:27 UTC, dborowiecki commented on claim_ai/evaluation/stored_resource_evaluation.py
> +    # @classmethod
Removed

2022-03-09 09:44 UTC, dragos-dobre approved these changes

2022-03-09 09:44 UTC, merged