OAI-34: Token authentication
openimis/openimis-be-claim_ai_py pull request #6
Opened 2021-01-25 18:35 UTC by dborowiecki

Depending on [OAI-32](https://github.com/openimis/openimis-be-claim_ai_py/pull/5)

TICKET: [OAI-34](https://openimis.atlassian.net/browse/OAI-34)

2021-01-26 16:31 UTC, dragos-dobre requested changes

2021-01-26 16:31 UTC, dragos-dobre commented on claim_ai/__init__.py
>  default_app_config = 'claim_ai.apps.ClaimAiConfig'
Is this line repeating on line 1?

2021-01-27 08:22 UTC, dborowiecki commented on claim_ai/__init__.py
>  default_app_config = 'claim_ai.apps.ClaimAiConfig'
It is, duplicate removed.

2021-01-27 15:25 UTC, dragos-dobre approved these changes

2021-01-27 15:25 UTC, merged